services:
  - type: web
    name: slidemath-ws
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node websocket.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
